name: Release DK IVI Docker Image
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        id: docker_login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TAG variable
        id: vars
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          GIT_TAG=${GITHUB_REF#refs/tags/}
          TAG="${SHORT_SHA}-${GIT_TAG}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "TAG=$TAG"  # output for debug
          echo "::set-output name=TAG::$TAG"

      - name: Prepare library directories
        run: |
          mkdir -p ./dreamos-core/dk-ivi-lite/src/library/target/amd64
          mkdir -p ./dreamos-core/dk-ivi-lite/src/library/target/arm64
          touch ./dreamos-core/dk-ivi-lite/src/library/target/amd64/.placeholder
          touch ./dreamos-core/dk-ivi-lite/src/library/target/arm64/.placeholder

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./dreamos-core/dk-ivi-lite
          file: ./dreamos-core/dk-ivi-lite/Dockerfile
          push: ${{ steps.docker_login.outcome == 'success' }}
          tags: |
            ghcr.io/${{ env.OWNER }}/dk_ivi:${{ env.TAG }}
            ghcr.io/${{ env.OWNER }}/dk_ivi:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            BUILDKIT_STEP_LOG_MAX_SIZE=10485760
            DOCKER_BUILDKIT=1
            BUILDKIT_STEP_LOG_MAX_SPEED=10485760

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
